### ISSUE TITLE
[LAB1] 请问代码中的LOSS就是似然函数的负数吗？看资料说是它的mean均值。

### ISSUE THREAD

**Issue by jiuzheyishi** [USTC-MLI-F23/Assignments#2]
请问代码中的LOSS就是似然函数的负数吗？看资料说是它的mean均值。

**Comment by USTC-MLI-F23** [comment]
损失可以理解成似然函数的负对数, sum和mean的形式都行,两者只差一个倍数,会影响优化时超参数的选择。推荐用mean的形式,这样无论数据集大小如何，平均损失都会在一个相似的范围内, 这使得学习率和其他超参数的选择变得更加容易。
