### ISSUE TITLE
[MLI-F23]HW解答未完全渲染

### ISSUE THREAD

**Issue by Smadx** [USTC-MLI-F23/Assignments#3]
# HW解答文件未完全渲染
HW文件夹中的两个作业解答.md文件中的latex公式未被完全渲染,例如HW1的第一题下面有红框:
`` The following macros are not allowed: \operatorname `` 
希望助教及时修改:crossed_fingers:
# 页面截图
![QQ截图20231024150953](https://github.com/USTC-MLI-F23/Assignments/assets/130368386/46cddf53-75a4-408d-ad74-7ac85d28448d)

**Comment by USTC-MLI-F23** [comment]
可以先下载下来, 换对latex公式支持更好的markdown编辑器查看, 也可以提pr

**Comment by USTC-MLI-F23** [comment]
已更新
